**HOMEWORK ONE**

**Question 1**

Question on Functions (20 Points)

a. Write a program that calculates the overtime pay using the following steps

Ask the user the total number of hours per week

Ask the user the base salary per week

Assume 40 hours per week and $45.00 per hour

In [8]:
def overtime_pay():
    num_hours = float(input("Enter the number of hours worked per week: "))
    base_salary = float(input("Enter the base salary per hour:"))
    overtime_pay_per_hours = 50
    base_hour_limit_per_week = 60
    hours_diff = num_hours - base_hour_limit_per_week
    if hours_diff > 0:
        Total_overtime_pay = hours_diff * overtime_pay_per_hours
    else:
        Total_overtime_pay = 0
    total_salary = Total_overtime_pay + base_salary
    print("The total Overtime pay is ${:.2f}".format(Total_overtime_pay))
    print("The total salary for the week inculding overtime is ${:.2f}".format(total_salary))
    return Total_overtime_pay

overtime_pay()


Enter the number of hours worked per week:  70
Enter the base salary per hour: 68


The total Overtime pay is $500.00
The total salary for the week inculding overtime is $568.00


500.0

**Question 2**

Question on List (20 Points)

a. Write a program that requests the user to a enter of list of 10 float values stored 
in variable name called mylist1 (note the values need to be ordered)

b. User list comprehension to recreate a new list of the same values from mylist1. 
The new list is called mylist2

c. Sort the values in mylist2

In [2]:
"""a"""
mylist1 = []
n = 10
for i in range(0, n):
   elm = int(input("Enter a number:"))
   mylist1.append(elm)
print("The entered list is: \n",mylist1)
"""b"""
mylist2 = [x for x in mylist1]
"""c"""
mylist2.sort()
mylist2



Enter a number: 5
Enter a number: 3
Enter a number: 5
Enter a number: 23
Enter a number: 56
Enter a number: 8
Enter a number: 9
Enter a number: 675
Enter a number: 45
Enter a number: 3


The entered list is: 
 [5, 3, 5, 23, 56, 8, 9, 675, 45, 3]


[3, 3, 5, 5, 8, 9, 23, 45, 56, 675]

**Question 3**

Question on Dictionary (15 Points)

a. Write a program that creates a single dictionary consisting of the following key-value pairs (name of dictionary- my_dict1)
School: MTSU, Textbooks: 14, Level: Elementary, Hobby:Dancing, Height:4.5inch,
Food: Amala

b. Update the dictionary with your credentials.
For example, change school to your actual school (former or current)

c. Add new key-pair values such as
Is_location_USA: True, is_graduated:No

d. Remove the key-value pair Hobby:Dancing and delete last entry of the updated 
dictionary.


In [3]:
"""a"""
my_dict1 = {"School":"MTSU", "Textbook":14, "Level":"Elementary", "Hobby":"Dancing", "Height":4.5, "Food":"Amala"}
"""b"""
my_dict1["School"] = "APSU"
my_dict1["Textbook"] = 10
my_dict1["Level"] = "Intermediate"
my_dict1["Hobby"] = "Movies"
my_dict1["Height"] = 6.3
my_dict1["Food"] = "Mac and cheese"
"""c"""
my_dict1["Is location USA"] = True
my_dict1["Is graduated"] = "No"
"""d"""
my_dict1.pop("Hobby")
my_dict1.popitem()

my_dict1

{'School': 'APSU',
 'Textbook': 10,
 'Level': 'Intermediate',
 'Height': 6.3,
 'Food': 'Mac and cheese',
 'Is location USA': True}

**Question 4**
Question Numpy (45 Points)

a. Create an array of ones of size 20 by 11 called myarray1

b. Multiply scalar of 0.5 by the array

c. Update the 6th row with a value of 10.5

d. Update the 7th row with a value of 11.5

e. Update the 1st column with a value of 9.5

f. Slice the 5th row to the 11th in myarry1

g. Slice the 6th column to 9th column in myarray1

h. Merge the 6th column with 8th column using np.hstack

i. Merge the 5th column with 10th column using np.vstack

In [4]:
import numpy as np
"""a"""
myarray1 = np.ones((20,11), dtype= float)
myarray1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.

In [5]:
"""b"""
myarray1 = 0.5 * myarray1
myarray1

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.

In [6]:
"""c"""
myarray1[5] = 10.5
myarray1

array([[ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,

In [13]:
"""d"""
myarray1[6] = 11.5

In [8]:
"""e"""
myarray1[:, 0:1] = 9.5
myarray1

array([[ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [ 9.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,

In [9]:
"""f"""
myarray1[4:12]

array([[ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [ 9.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5]])

In [10]:
"""g"""
myarray1[:,6:10]

array([[ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [10.5, 10.5, 10.5, 10.5],
       [11.5, 11.5, 11.5, 11.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5]])

In [11]:
"""h"""
h_arr = np.hstack((myarray1[6],myarray1[8]))
h_arr

array([ 9.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5,
        9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5])

In [12]:
"""i"""
v_arr = np.vstack((myarray1[5],myarray1[10]))
v_arr

array([[ 9.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5]])